kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: anthonys-test-pvc
  labels:
    type: amazonEBS
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
  storageClassName: gp2
